# Generated by Django 3.2.9 on 2021-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id_product_type', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id_product_provider', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('bar_code', models.CharField(max_length=45)),
                ('fk_id_product', models.ForeignKey(db_column='fk_id_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('fk_id_provider', models.ForeignKey(db_column='fk_id_provider', on_delete=django.db.models.deletion.DO_NOTHING, to='provider.provider')),
            ],
            options={
                'db_table': 'product_provider',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fk_id_product_type',
            field=models.ForeignKey(db_column='fk_id_product_type', on_delete=django.db.models.deletion.DO_NOTHING, to='product.producttype'),
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id_price_product', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('start_date', models.DateField()),
                ('user_update', models.CharField(max_length=40)),
                ('date_update', models.DateField()),
                ('fk_id_product_provider', models.ForeignKey(db_column='fk_id_product_provider', on_delete=django.db.models.deletion.DO_NOTHING, to='product.productprovider')),
            ],
            options={
                'db_table': 'price_product',
                'managed': True,
            },
        ),
    ]
