# Generated by Django 3.2.9 on 2021-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=45)),
                ('url', models.CharField(blank=True, max_length=45, null=True)),
                ('nit', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'provider',
                'managed': True,
            },
        ),
    ]
