# Generated by Django 3.2.9 on 2021-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id_tax', models.AutoField(primary_key=True, serialize=False)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_name', models.CharField(max_length=15)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tax',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TaxPriceProduct',
            fields=[
                ('id_tax_price_product', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_price_product', models.ForeignKey(db_column='fk_id_price_product', on_delete=django.db.models.deletion.DO_NOTHING, to='product.priceproduct')),
                ('fk_id_tax', models.ForeignKey(db_column='fk_id_tax', on_delete=django.db.models.deletion.DO_NOTHING, to='tax.tax')),
            ],
            options={
                'db_table': 'tax_price_product',
                'managed': True,
            },
        ),
    ]
