# Generated by Django 3.2.9 on 2021-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=45, null=True)),
                ('person_last_name', models.CharField(max_length=45)),
                ('person_address', models.CharField(blank=True, max_length=45, null=True)),
                ('person_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('person_dni', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id_person_type', models.AutoField(primary_key=True, serialize=False)),
                ('person_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'person_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonPersonType',
            fields=[
                ('id_person_person_type', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_person', models.ForeignKey(db_column='fk_id_person', on_delete=django.db.models.deletion.DO_NOTHING, to='persons.person')),
                ('fk_id_person_type', models.ForeignKey(db_column='fk_id_person_type', on_delete=django.db.models.deletion.DO_NOTHING, to='persons.persontype')),
            ],
            options={
                'db_table': 'person_person_type',
                'managed': True,
            },
        ),
    ]
