# Generated by Django 3.2.9 on 2021-11-15 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateField()),
                ('half_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fk_id_person_cashier', models.ForeignKey(db_column='fk_id_person_cashier', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_id_person_cashier', to='persons.person')),
                ('fk_id_person_customer', models.ForeignKey(db_column='fk_id_person_customer', on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_id_person_customer', to='persons.person')),
            ],
            options={
                'db_table': 'ticket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id_ticket_detail', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('devolution_request', models.DateField(blank=True, null=True)),
                ('devolution_approved', models.DateField(blank=True, null=True)),
                ('description_devolution', models.CharField(blank=True, max_length=45, null=True)),
                ('fk_id_person_administrator', models.ForeignKey(blank=True, db_column='fk_id_person_administrator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='persons.person')),
                ('fk_id_tax_price_product', models.ForeignKey(db_column='fk_id_tax_price_product', on_delete=django.db.models.deletion.DO_NOTHING, to='tax.taxpriceproduct')),
                ('fk_id_ticket', models.ForeignKey(db_column='fk_id_ticket', on_delete=django.db.models.deletion.DO_NOTHING, to='ticket.ticket')),
            ],
            options={
                'db_table': 'ticket_detail',
                'managed': True,
            },
        ),
    ]
